/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppTreasuryRouteImport } from './routes/app.treasury'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppRhRouteImport } from './routes/app.rh'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAgentsRouteImport } from './routes/app.agents'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTreasuryRoute = AppTreasuryRouteImport.update({
  id: '/app/treasury',
  path: '/app/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/app/tasks',
  path: '/app/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRhRoute = AppRhRouteImport.update({
  id: '/app/rh',
  path: '/app/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/app/projects',
  path: '/app/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/app/knowledge',
  path: '/app/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/app/agents',
  path: '/app/agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRoute
  '/login': typeof LoginRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/rh': typeof AppRhRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/treasury': typeof AppTreasuryRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRoute
  '/login': typeof LoginRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/rh': typeof AppRhRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/treasury': typeof AppTreasuryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRoute
  '/login': typeof LoginRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/rh': typeof AppRhRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/treasury': typeof AppTreasuryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app/agents'
    | '/app/dashboard'
    | '/app/knowledge'
    | '/app/projects'
    | '/app/rh'
    | '/app/tasks'
    | '/app/treasury'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/agents'
    | '/app/dashboard'
    | '/app/knowledge'
    | '/app/projects'
    | '/app/rh'
    | '/app/tasks'
    | '/app/treasury'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/app/agents'
    | '/app/dashboard'
    | '/app/knowledge'
    | '/app/projects'
    | '/app/rh'
    | '/app/tasks'
    | '/app/treasury'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppRhRoute: typeof AppRhRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTreasuryRoute: typeof AppTreasuryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/treasury': {
      id: '/app/treasury'
      path: '/app/treasury'
      fullPath: '/app/treasury'
      preLoaderRoute: typeof AppTreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/app/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rh': {
      id: '/app/rh'
      path: '/app/rh'
      fullPath: '/app/rh'
      preLoaderRoute: typeof AppRhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/app/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/app/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/app/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppRhRoute: AppRhRoute,
  AppTasksRoute: AppTasksRoute,
  AppTreasuryRoute: AppTreasuryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
